[book]
authors = ["Harry Han"]
language = "en"
multilingual = false
src = "src"
title = "Guide for Self-studying Coding"

[output.html]
mathjax-support = true
curly-quotes = true
additional-css = [
  "theme/css/speaker-notes.css",
]
fold.enable = true
